# Generated by Django 3.2.5 on 2022-01-21 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('quantity', models.BigIntegerField()),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('forecast_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Display.item')),
            ],
            options={
                'unique_together': {('forecast_item', 'month')},
            },
        ),
    ]
